#!/bin/bash
# This hook is sourced after every virtualenv is activated.

export PS1="(\[\033[1;37m\]\d \t\[\033[0m\]) (\[\033[0;35m\]`basename $VIRTUAL_ENV`\[\033[0m\]) \[\033[0;31m\]\u\[\033[0m\]\[\033[0;36m\]@\h\[\033[0m\]\[\033[0;37m\]\w\[\033[0m\]\$ "
